version: "3.8"

services:

  mqtt:
    #image: mjenz/rpi-mosquitto:latest
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      example-network:  
        ipv4_address: 172.16.238.12
        
  backend:
    image: flask
    container_name: flask-backend
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      example-network:
        ipv4_address: 172.16.238.13

  frontend:
    # image: nextjs
    image: jokley/disti-nextjs
    container_name: next-frontend
    privileged: true
    #build:
      #context: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      example-network:
        ipv4_address: 172.16.238.14
        
        
  nginx:
    image: arm32v6/nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      example-network:
        ipv4_address: 172.16.238.15

networks:
  example-network:
    name: example-network
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 172.16.238.0/24

volumes:
  db_data:
  pgadmin-data:
