version: "3.8"

services:
  fhem: 
    image: fhem/fhem:latest
    restart: unless-stopped
    privileged: true
    ports:
        - "8083:8083"
        - "7072:7072"
    volumes:
        - ./fhem/:/opt/fhem/
        - /sys:/sys
    networks:
       example-network:
            ipv4_address: 172.16.238.10
    devices:
        - "/dev/ttyAMA0:/dev/ttyAMA0"
        - "/dev/gpiomem:/dev/gpiomem"
    environment:
        FHEM_UID: 1000
        FHEM_GID: 1000
        GPIO_GID: 997
        TIMEOUT: 10
        RESTART: 1
        TELNETPORT: 7072
        TZ: Europe/Berlin  

  nginx:
    image: arm32v6/nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./nginx/.htpasswd /etc/nginx/.htpasswd
       - ./wwwroot:/var/www/root
    networks:
      example-network:
        ipv4_address: 172.16.238.15

networks:
  example-network:
    name: example-network
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 172.16.238.0/24
